config/routes.rb
Rails.application.routes.draw do
  root to: 'topics#index'
  resources :topics
  resources :comments, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :topic

  validates :name, length: { in: 1..15 }
  validates :body, length: { in: 1..280 }
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, length: { in: 1..45 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def create_comments_hash
    # コメントと番号をハッシュで関連付ける
    comment_hash = {}
    @topic.comments.all.each_with_index { |comment, i|  comment_hash.store(i + 1, comment) }
    create_sets_by_hierarchy(comment_hash)
  end

  # 返信コメントの階層ごとの集合を作成する
  def create_sets_by_hierarchy(comment_hash)
    normal_comment_list = nil
    n_lebel_reply_hash_list = []
    n = 0

    loop do
      if n.zero?
        # reply_pathがnilのもの、つまり返信でない普通のコメントの集合を"配列で"作る
        normal_comment_list = comment_hash.select { |k, v| v.reply_path.nil? }.to_a
      else
        # reply_pathがn階層の集合を"ハッシュで"作る
        tmp = comment_hash.select { |k, v| v.reply_path.present? && v.reply_path.split('/').length == n }
        # n階層目の集合がない場合は空のハッシュが帰るので、lengthが0なら終了
        tmp.length.zero? ? break : n_lebel_reply_hash_list << tmp
      end
      n += 1
    end

    # 例
    # p normal_comment_list
    #=> [[1, reply_path: nil], [2, reply_path: nil], [8, reply_path: nil]]
    # p n_lebel_reply_hash_list
    #=> [{3=>reply_path: "2", 7=>reply_path: "2"}, {4=>reply_path: "2/3", 5=>reply_path: "2/3"}, {6=>reply_path: "2/3/4"}]
    sort_correct_order_with(normal_comment_list, n_lebel_reply_hash_list)
  end

  # n階層までの返信コメントを正しい順に並び替えた配列を作成する再帰的な関数
  def sort_correct_order_with(current_comment_list, n_lebel_reply_hash_list)
    sorted_list = []
    current_comment_list.each do |comment|
      sorted_list << comment

      reply_hash_list = []
      # n階層目の返信コメがある場合、i番目のコメに返信している返信コメの集合を作る
      unless n_lebel_reply_hash_list.length.zero?
        reply_hash_list = n_lebel_reply_hash_list.first.select do |k, v|
          # comment.firstでコメントと紐付いている番号を取得
          v.reply_path.split('/').last == comment.first.to_s
        end
      end

      unless reply_hash_list.length.zero?
        # 配列上の親コメントの次に子(返信)コメントを挿入する
        reply_hash_list.to_a.each_with_index do |reply, i|
          sorted_list.insert(sorted_list.index(comment) + i + 1, reply)
        end
      end
    end

    # 先頭を削除し、返信コメントの集合が無くなったら終わり
    n_lebel_reply_hash_list.shift
    if n_lebel_reply_hash_list.length.zero?
      sorted_list
    else
      sort_correct_order_with(sorted_list, n_lebel_reply_hash_list)
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @topic = Topic.find(session[:topic_id])
    @comment = @topic.comments.build(comment_params)
    @comment.name = '匿名' if @comment.name.length.zero?

    if @comment.save
      flash[:success] = 'コメントを投稿しました！'
      redirect_to @topic
    else
      @comments = create_comments_hash
      render 'topics/show'
    end
  end

  def destroy
    # 親コメントが削除された場合、それへの返信コメントも削除する
    topic = Topic.find(session[:topic_id])
    comment = Comment.find(params[:id])
    reply_comment_destroy(topic, comment)
    comment.destroy
    redirect_to topic, notice: "コメントを削除しました。"
  end

  private

    def comment_params
      params.require(:comment).permit(:name, :body, :reply_path)
    end

    def reply_comment_destroy(topic, parent_comment)
      all_comments = topic.comments.all
      # 掲示板内でのコメント番号を検索
      p_comment_num = all_comments.index(parent_comment) + 1

      # 自分のコメントへの返信コメントのパスを作成する
      # 通常コメントなら自分の番号を、返信コメントならreply_path + 自分の番号
      reply_path = p_comment_num.to_s
      reply_path = "#{parent_comment.reply_path}/#{p_comment_num}" if parent_comment.reply_path.present?

      all_comments.select { |comment|
        comment.reply_path == reply_path || /#{reply_path.delete('/')}\d.*/ === comment.reply_path&.delete('/')
      }.each(&:destroy)
    end

  # private
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
    @comment = @topic.comments.build
    @comments = create_comments_hash
    session[:topic_id] = @topic.id
  end

  def new
    @topic = Topic.new
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      redirect_to @topic, notice: "スレッド「#{@topic.title}」を投稿しました。"
    else
      render :new
    end
  end

  def update
    topic = Topic.find(params[:id])
    topic.update!(topic_params)
    redirect_to topics_url, notice: "スレッド「#{topic.title}」を更新しました。"
  end

  def destroy
    topic = Topic.find(params[:id])
    topic.destroy
    redirect_to topics_url, notice: "スレッド「#{topic.title}」を削除しました。"
  end

  private

    def topic_params
      params.require(:topic).permit(:title)
    end

  # private
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | BulletinBoard
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand BulletinBoard
    .container.mt-2
      - if flash.notice.present?
        .alert.alert-success= flash.notice
      = yield

app/views/topics/edit.html.slim
h1 トピックの変更

.nav.justify-content-end
  = link_to '一覧へ', topics_path, class: 'nav-link my-3'

= form_with model: @topic, local: true do |f|
  .form-group
    = f.label 'タイトル'
    = f.text_field :title, class: 'form-control', id: 'title_name'
  = f.submit '更新', class: 'btn btn-primary'

app/views/topics/index.html.slim
h1 スレッド一覧

= link_to '新規スレッド', new_topic_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th タイトル
      th 投稿日時
      th
  tbody
    - @topics.each do |topic|
      tr
        td= link_to topic.title, topic_path(topic)
        td= topic.created_at
        td
          = link_to '編集', edit_topic_path(topic), class: 'btn btn-primary mr-3'
          = link_to '削除', topic, method: :delete, data: { confirm: "タスク「#{topic.title}」を削除します。よろしいですか？" },
          class: 'btn btn-danger'

app/views/topics/new.html.slim
- if @topic.errors.present?
  ul#error_explanation
    - @topic.errors.full_messages.each do |message|
      li= message

h1 スレッドの新規作成

.nav.justify-content-end
  = link_to '一覧へ', topics_path, class: 'nav-link'

= form_with model: @topic, local: true do |f|
  .form-group
    = f.label 'タイトル'
    = f.text_field :title, class: 'form-control', id: 'title_name'
  = f.submit '作成', class: 'btn btn-primary'

app/views/topics/show.html.slim
= @x
  / li= i.name

- if flash[:success].present?
  .alert.alert-success= flash[:success]

- if @comment.errors.present?
  ul#error_explanation
    - @comment.errors.full_messages.each do |message|
      li= message

.nav.justify-content-end
  = link_to '一覧へ', topics_path, class: 'nav-link my-3'

.d-flex.justify-content-between.mb-4
  h2= @topic.title
  div.mt-2
    = link_to '編集', edit_topic_path(@topic), class: 'btn btn-primary mr-3'
    = link_to '削除', @topic, method: :delete, data: { confirm: "タスク「#{@topic.title}」を削除します。よろしいですか？" },
      class: 'btn btn-danger'

- if @comments.any?
  - ct = 0
  - @comments.each do |i, comment|
    .comment-wrapper
      .d-flex.justify-content-between.border.my-2.p-2
        div
          span= "#{i}：#{comment.name}  #{comment.created_at}"
          br
          span= simple_format(h(comment.body))
          br
          span.hierarchy_depth_retention style="display: none;"= comment.reply_path.present? ? comment.reply_path.split('/').length : 0
        .d-flex
          div= link_to '返信', nil, class: 'btn btn-outline-secondary mt-1 mr-2', onclick: "replyFormToggle(#{ct}); return false"
          div= link_to '削除', comment, method: :delete, data: { confirm: "コメントを削除しますか？" }, class: 'btn btn-outline-danger mt-1'
      .reply-form
        - reply_path = comment.reply_path.nil? ? "#{i}" : "#{comment.reply_path}/#{i}"
        = form_with model: @comment, local: true do |f|
          = f.hidden_field :reply_path, value: reply_path
          .form-group
            = f.text_field :name, class: 'form-control', id: 'name', placeholder: '名前'
          .form-group
            = f.text_area :body, class: 'form-control', id: 'body', placeholder: '本文', size: "10x3"
          = f.submit '返信', class: 'btn btn-primary mb-3'
    - ct += 1

- else
  p
    i.text-muted まだコメントはありません
p.mt-5
  b コメントを投稿する

= form_with model: @comment, local: true do |f|
  .form-group
    = f.text_field :name, class: 'form-control', id: 'name', placeholder: '名前'
  .form-group
    = f.text_area :body, class: 'form-control', id: 'body', placeholder: '本文', size: "10x7"
  = f.submit '投稿', class: 'btn btn-primary mb-3'

javascript:
  const replyFormList = document.querySelectorAll('.reply-form')
  const replyFormToggle = i => {
    replyFormList[i].style.display = replyFormList[i].style.display === 'block' ? 'none' : 'block'
  }

  const commentWrapperList = document.querySelectorAll('.comment-wrapper')

  commentWrapperList.forEach(comment => {
    const hierarchyDepth = Number(comment.querySelector('.hierarchy_depth_retention').textContent)
    if (hierarchyDepth < 6) {
      comment.style.marginLeft = `${hierarchyDepth * 60}px`
    }
  })